# Login page selectors
login.usernameInput=#user-name
login.passwordInput=#password
login.loginButton=#login-button

# Product page selectors
product.addButton=div.inventory_item:has-text('%s') button.btn_inventory
product.cartLink=.shopping_cart_link

# Checkout page selectors
checkout.checkoutButton=button[id='checkout']
checkout.firstName=#first-name
checkout.lastName=#last-name
checkout.postalCode=#postal-code
checkout.continueButton=#continue
checkout.finishButton=#finish
checkout.confirmationMessage=.complete-header
